Update version to 1.6.1-rc1
Also removing the last two patches added based on the discussion here
which is causing test failures.

https://github.com/s3tools/s3cmd/pull/599#issuecomment-148219177

All tests pass on oslo-00, except 1 where it was trying to list a bucket
where the run user didn't have the right permission, so skipping that
one.

puneet@oslo-00:~/repositories/s3cmd$ ./run-tests.py -68
System encoding: UTF-8
Using bucket prefix: 'puneet-'
  1  Remove test buckets ..... OK
  2  Verify no test buckets .. OK
  3  Create one bucket (EU) .. OK
  4  Create multiple buckets . OK
  5  Invalid bucket name ..... OK
  6  Buckets list ............ OK
  7  Sync to S3 .............. OK
  8  Sync UTF-8 to S3 ........ OK
  9  List bucket content ..... OK
 10  List bucket recursive ... OK
 11  Clean testsuite-out/(rm)  OK
 12  Clean testsuite-out/(mk)  OK
 13  Put from stdin .......... OK
 14  Put multipart ........... OK
 15  Multipart large put from stdin  OK
 16  Clean testsuite-out/(rm)  OK
 17  Clean testsuite-out/(mk)  OK
 18  Sync from S3 ............ OK
 19  Remove 'dir-test/' ...... OK
 20  Create file-dir dir ..... OK
 21  Skip over dir ........... OK
 22  Clean testsuite-out/(rm)  OK
 23  Clean testsuite-out/(mk)  OK
 24  Put public, guess MIME .. OK
 25  Retrieve from URL ....... OK
 26  Change ACL to Private ... OK
 27  Verify Private ACL ...... OK
 28  Change ACL to Public .... OK
 29  Verify Public ACL ....... OK
 30  Sync more to S3 ......... OK
 31  Change file cksum1.txt .. OK
 32  Change file cksum33.txt . OK
 33  Don't check MD5 ......... OK
 34  Check MD5 ............... OK
 35  Rename within S3 ........ OK
 36  Rename (NoSuchKey) ...... OK
 37  Sync more from S3 (invalid src)  OK
 38  Sync more from S3 ....... OK
 39  Remove dst dir for get .. OK
 40  Get multiple files ...... OK
 41  Put unicode filenames ... OK
 42  Make dst dir for get .... OK
 43  Get unicode filenames ... OK
 44  Get multiple files ...... OK
 45  blah.txt / Blah.txt ..... OK
 46  Copy between buckets .... OK
 47  Recursive copy, set ACL . OK
 48  Verify ACL and MIME type  OK
 49  Modify MIME type ........ OK
 50  Verify ACL and MIME type  OK
 51  Modify MIME type back ... OK
 52  Verify ACL and MIME type  OK
 53  Add cache-control header  OK
 54  HEAD check Cache-Control present  OK
 55  Remove cache-control header  OK
 56  HEAD check Cache-Control not present  OK
 57  sign string ............. OK
 58  signurl time ............ OK
 59  signurl time offset ..... OK
 60  signurl content disposition and type  OK
 61  Rename within S3 ........ OK
 62  Sync remote2remote ...... OK
 63  Don't put symbolic links  OK
 64  Put symbolic links ...... OK
 65  Sync symbolic links ..... OK
 66  Multi-source move ....... OK
 67  Verify move ............. OK
 68  List all ................ SKIP
 69  Simple delete ........... OK
 70  Simple delete with rm ... OK
 71  Create expiration rule with days and prefix  OK
 72  Create expiration rule with date and prefix  OK
 73  Create expiration rule with days only  OK
 74  Create expiration rule with date only  OK
 75  Get current expiration setting  OK
 76  Delete expiration rule .. OK
 77  Set requester pays ...... OK
 78  Get requester pays flag . OK
 79  ls using requester pays flag  OK
 80  Clear requester pays .... OK
 81  Get requester pays flag . OK
 82  Recursive delete maximum exceeded  OK
 83  Recursive delete ........ OK
 84  Recursive delete with rm  OK
 85  Recursive delete all .... OK
 86  Remove empty bucket ..... OK
 87  Remove remaining buckets  OK

In case you wanted to check, the skipped test output:

68  List all ................ FAIL  ('retcode: 77, expected one of:
[0]')
----
python2 s3cmd -c /home/puneet/.s3cfg la
----

                       DIR   s3://bina.aws.dev-eng.cloudtrail/AWSLogs/

2015-10-02 15:53  78729295
s3://bina.aws.dev-eng.debug-logs/portal-debug-logs.tar.gz

                       DIR
s3://bina.aws.dev-eng.deployment-archive/confs/
                       DIR
s3://bina.aws.dev-eng.deployment-archive/templates/
2015-08-27 18:26 128434226
s3://bina.aws.dev-eng.deployment-archive/bina-portal-database_v2.6.3.tar.gz
2015-08-27 18:27        77
s3://bina.aws.dev-eng.deployment-archive/bina-portal-database_v2.6.3.tar.gz.SHA1SUM
2015-09-17 16:00 127461695
s3://bina.aws.dev-eng.deployment-archive/bina-portal-database_v2.7.1.tar.gz
2015-09-17 16:01        77
s3://bina.aws.dev-eng.deployment-archive/bina-portal-database_v2.7.1.tar.gz.SHA1SUM
2015-09-18 04:51 127471033
s3://bina.aws.dev-eng.deployment-archive/bina-portal-database_v2.7.2.tar.gz
2015-09-18 04:52        77
s3://bina.aws.dev-eng.deployment-archive/bina-portal-database_v2.7.2.tar.gz.SHA1SUM
2015-10-10 22:42 127448722
s3://bina.aws.dev-eng.deployment-archive/bina-portal-database_v2.7.3.tar.gz
2015-10-10 22:43        77
s3://bina.aws.dev-eng.deployment-archive/bina-portal-database_v2.7.3.tar.gz.SHA1SUM
2015-08-27 18:27 939014355
s3://bina.aws.dev-eng.deployment-archive/bina_v2.4.4.tar.gz
2015-08-27 18:29        61
s3://bina.aws.dev-eng.deployment-archive/bina_v2.4.4.tar.gz.SHA1SUM
2015-08-27 18:29 2349373872
s3://bina.aws.dev-eng.deployment-archive/bina_v2.6.3.tar.gz
2015-08-27 18:35        61
s3://bina.aws.dev-eng.deployment-archive/bina_v2.6.3.tar.gz.SHA1SUM
2015-09-17 16:01 2670552313
s3://bina.aws.dev-eng.deployment-archive/bina_v2.7.1.tar.gz
2015-09-17 16:08        61
s3://bina.aws.dev-eng.deployment-archive/bina_v2.7.1.tar.gz.SHA1SUM
2015-09-18 04:37 2675196948
s3://bina.aws.dev-eng.deployment-archive/bina_v2.7.2.tar.gz
2015-09-18 04:51        61
s3://bina.aws.dev-eng.deployment-archive/bina_v2.7.2.tar.gz.SHA1SUM
2015-10-10 22:34 2684332849
s3://bina.aws.dev-eng.deployment-archive/bina_v2.7.3.tar.gz
2015-10-10 22:42        61
s3://bina.aws.dev-eng.deployment-archive/bina_v2.7.3.tar.gz.SHA1SUM
2015-09-18 04:34        65
s3://bina.aws.dev-eng.deployment-archive/templates

ERROR: Access to bucket 'bina.aws.dev-eng.encdec-testdata' was denied
ERROR: S3 error: 403 (AccessDenied): Access Denied